### ISSUE TITLE
[benchmark] Abstruse vs. rest of OSS

### ISSUE THREAD

**Issue by irmana** [bleenco/abstruse#134]
Primary list of CIs: Abstruse, Jenkins

Secondary list of CIs: Drone, Strider, Go, Integrity

We first setup one by one on the same machine and benchmark separately on the following criteria:

* First time user, first time installation: Start time is when the webpage is opened, end is when the first repo is successfully added.
* Concurrent builds, average of 3 sequential builds: benchmarking time, server resources usage (memory, processor etc.)

------ EDIT ------

List of benchmarked CIs:
- [x] Abstruse 1.0.0
- [x] Jenkins 2.60.3
- [ ] Drone
- [ ] Strider
- [ ] Go

**Comment by Izak88** [comment]
Features Abstruse vs Jenkins:

|  **Feature** | **Abstruse** | **Jenkins** |
|---	|---	|---   |
|   Unlimited concurrent job   	|   Y	|   Y	|
|   Unlimited build minutes	|   Y	|   Y	|
|   Unlimited repositories	|  Y 	|   Y	|
|   Unlimited collaborators	|  Y 	|   Y	|
|   Open source	|  Y 	|  Y 	|
|   Public / Private builds	|  Y 	|  Y	|
|   Public / Private repositories	|  Y 	|   Y	|
|   Integration with Github, Gitlab, Gogs, Bitbucket	|  Y 	|   Y	|
|   Nice, simple web interface	|  Y 	|   N	|
|   Free	|  Y 	|   Y	|
|   SSH mode to access container and make your own investigation	|  Y 	|   N	|
|   Complete out of a box solution that needs minimal configuration\adjustments	|  Y 	|   N	|
|   Compatible with Mac OS X, Windows, Linux	|  Y 	|   Y	|
|   Support for X programming languages	|  Y 	|   Y	|
|   Lightweight, easily readable YAML config	|  Y 	|   N	|
|   Options to run tests on Linux, Windows, Mac OS X at the same time	|  Y 	|   N	|
|   Support of build matrix (run tests with different versions of language and packages at the same time)	|  Y 	|   N	|
|   Full control of the system (runs on own servers)	|  Y 	|   Y	|
|   Statistics for server resource consumption, runned jobs	|  Y 	|   N	|

**Comment by Izak88** [comment]
Benchmarking (installation and preparation):

|  **Feature** | **Abstruse** | **Jenkins** |
|   Server installation	|  5m 10s |  8m 30s	|
|   Start First Build	|  5m 10s |   8m |
|   Configura auto builds	|  0s |   45m |

**Comment by Izak88** [comment]
Benchmarking Abstruse vs Jenkins:

|  **Java-Design-Patterns** | **Total Average** | **Start Build** | **Clone** | **mvn install** | **test** |
|---	|---	|---   |--- |--- |--- |
|   Jenkins	|  4m 27s |  9s	| 21s | 2m 32s | 1m 25s |
|   Abstruse	|  3m 18s |  1s | 15s |  2m 14s | 49s |

|  **Angular build** | **Total Average** | **Start Build** | **Clone** | **npm install** | **build** |
|---	|---	|---   |--- |--- |--- |
|   Jenkins	|  3m 10s |  30s | 44s | 14s | 1m 42s |
|   Abstruse	|  2m 30s |  1s | 32s |  18s | 1m 41s |

|  **Angular test 1** | **Total Average** | **Start Build** | **Clone** | **npm install** | **test** |
|---	|---	|---   |--- |--- |--- |
|   Jenkins	|  5m 13s |  32s | 47s | 15s | 3m 39s |
|   Abstruse	|  4m 53s |  1s | 30s |  18s | 4m 5s |

|  **Angular test 2** | **Total Average** | **Start Build** | **Clone** | **npm install** | **test** |
|---	|---	|---   |--- |--- |--- |
|   Jenkins	|  7m 36s |  29s | 48s | 17s | 5m 59s |
|   Abstruse	|  5m 55s |  1s | 43s |  17s | 4m 52s |

|  **D3-bundle** | **Total Average** | **Start Build** | **Clone** | **npm install** | **test** |
|---	|---	|---   |--- |--- |--- |
|   Jenkins	|  54s |  18s | 27s | 7s | 1s |
|   Abstruse	|  33s |  1s | 26s |  5s | 1s |

**Comment by Izak88** [comment]
**Resource consumptions Abstruse vs Jenkins:**

Java Project:
-Abstruse 
-Jenkins ([run 1](https://docs.google.com/spreadsheets/d/1RW4kT9FsKdnbAqpmxhtp-wsE85R5ImNa_bvr6eDAyUw/edit?usp=sharing), [run 2](https://docs.google.com/spreadsheets/d/1f9ZC-SQsZy_FymdqApPqWllWtr3tnf_IhpnRndIvC_s/edit?usp=sharing), [run 3](https://docs.google.com/spreadsheets/d/1QsuCUHEWupT2cIMMC8BNAA0WWs1cEc7jldaGq_5VAZ0/edit?usp=sharing))

Angular Project:
-Abstruse ([run 1](https://docs.google.com/spreadsheets/d/1K4bocrTZsBiMDaZJrI30Pr0Dw1J2Bt9KAn_dmaXe3nc/edit?usp=sharing), [run 2](https://docs.google.com/spreadsheets/d/1KYecddJCs6mCSNJdfvROkfpbfl6olnosskwu8TL4YOA/edit?usp=sharing))
-Jenkins ([run 1](https://docs.google.com/spreadsheets/d/1yhxD4chftrwQOrXO_o7h1cZtayC_x_mh06SHVlFJppE/edit?usp=sharing), [run 2](https://docs.google.com/spreadsheets/d/1nZSlLSVM4-wD8bbGBrjSfJJ3Ij8geUvit6ExRUXjZmo/edit?usp=sharing))

D3-bundle Project:
-Abstruse ([run 1](https://docs.google.com/spreadsheets/d/1qEUUIA4SrZT2MX4XkP4eFGD2dZgfrlSsqOE0-Lr9rLk/edit?usp=sharing), [run 2](https://docs.google.com/spreadsheets/d/1qG7ljSIyZI28OnCIdt1JJ9OtChntknqVFYjlsp3qkvI/edit?usp=sharing))
-Jenkins  ([run 1](https://docs.google.com/spreadsheets/d/1_ujQW96w3cltQGN1B7H1QvVIf6olHox_Ke8n4BdXg3Y/edit?usp=sharing), [run 2](https://docs.google.com/spreadsheets/d/1qG7ljSIyZI28OnCIdt1JJ9OtChntknqVFYjlsp3qkvI/edit?usp=sharing), [run 3](https://docs.google.com/spreadsheets/d/1HnPaABVbxWYcOH3cm9hUUBjTXXh4w6UTX4-0UFJ15QY/edit?usp=sharing))


All measurements were captured in same conditions on a server with:
-CPU Intel i7-4700HQ @ 2.40GHz
-Memory 12GB DDR3 1600 MHz

**Comment by irmana** [comment]
![abstruse-jenkins-ang](https://user-images.githubusercontent.com/3041169/31200825-a2b3ab3c-a95c-11e7-9d0e-7c48af6730f9.jpg)
![abstruse-jenkins-jdp](https://user-images.githubusercontent.com/3041169/31200826-a2b4292c-a95c-11e7-8d73-c395f7b37355.jpg)

**Comment by irmana** [comment]
This benchmark is no longer necessary.

**Comment by DblK** [comment]
I think the comparison against secondary list of CIs can be a good way to decide to use this one.
Any update about this one?
