### ISSUE TITLE
[feat]: badges

### ISSUE THREAD

**Issue by Izak88** [bleenco/abstruse#223]
- [ ] add new badges (number of builds, version...)
- [ ] correct current badges (too little indentation...)  (high priority)

**Comment by matthax** [comment]
Any thoughts on badges for tests? Should that just be left to the testing suite?

**Comment by irmana** [comment]
@jkuri don't we have correct badges (too little indentation...) fixed? Also, do you think it's possible to squeeze in badges for number of builds, version etc. into 2.0?

**Comment by jkuri** [comment]
yes if we use 3rdparty lib, https://github.com/amio/badgen seems promising.
