### ISSUE TITLE
[feat]: Deploy steps

### ISSUE THREAD

**Issue by Izak88** [bleenco/abstruse#230]
- [ ] deploy only if build was successful (critical)
- [x] right sequence for deploy scripts (high)

**Comment by Izak88** [comment]
![build_image](https://user-images.githubusercontent.com/8555269/32659383-cac43400-c61e-11e7-8990-d7a70fdf4c43.png)

**Comment by jkuri** [comment]
why does this editor doesn't have Dockerfile syntax highlighting, has unnecessary minimap on right side and probably some other unconsistent things from previous editor?
Please make dropdown narrower, this full width looks nasty.
