### ISSUE TITLE
[feat]: deployment services integration

### ISSUE THREAD

**Issue by Izak88** [bleenco/abstruse#231]
- [ ] anynines
- [ ] Appfog
- [ ] Atlas
- [x] **AWS CodeDeploy**
- [x] **AWS Elastic Beanstalk**
- [ ] **AWS Lambda**
- [ ] **AWS OpsWorks**
- [x] **AWS S3**
- [ ] **Azure Web Apps**
- [ ] bintray
- [ ] BitBalloon
- [ ] Bluemix CloudFoundry
- [ ] Boxfuse
- [ ] Catalyze
- [ ] Chef Supermarket
- [ ] Cloud 66
- [ ] **CloudFoundry**
- [ ] Deis
- [ ] Engine Yard
- [ ] **GitHub Pages**
- [ ] **GitHub Releases**
- [ ] **Google App Engine**
- [ ] **Google Cloud Storage**
- [ ] **Google Firebase**
- [ ] Hackage
- [ ] **Heroku**
- [ ] **Launchpad**
- [ ] Modulus
- [ ] **npm**
- [ ] OpenShift
- [ ] packagecloud.io
- [ ] Puppet Forge
- [ ] PyPI
- [ ] **Rackspace Cloud Files**
- [ ] RubyGems
- [ ] Scalingo
- [ ] Script
- [ ] Surge.sh
- [ ] TestFairy
- [ ] Uploading Build Artifacts
*Additionally:*
- [ ] check for others deployment services
- [ ] find a way to test this integrations (mock api?)

**Comment by matthax** [comment]
Just opened #358 thought it would be good to have a separate issue for discussion.
