### ISSUE TITLE
Handling of failing Image Build

### ISSUE THREAD

**Issue by ComiR** [bleenco/abstruse#241]
I just tried out abstruse for the first time using the docker image. Works nicely.

Then I went on to create a Docker Build Image with abstruse and naturally I copy & pasted parts of an existing Dockerfile of ours into the "user section" of the provided template. As expected the build failed.

Now I am "stuck" at "Building image nameless_image (5/5 layers) ...". Nothing tells me that it is done doing anything. There should be some message that the build failed.

What is most annoying is that I can't go back to the Dockerfile to change sth, but must start from scratch.

**Comment by Izak88** [comment]
Thanks, for using our product!
You're right, there should be some message, that building image failed. We'll try to correct that as soon as possible.
