### ISSUE TITLE
Default Image not getting shown

### ISSUE THREAD

**Issue by ComiR** [bleenco/abstruse#242]
After trying with a modified version of the default template (see #241), I just used the default template to build an Image. It did work as `docker image ls` shows me `nameless_image                                                latest              65d13974819a        18 minutes ago      925MB`, but in abstruse the Image doesn't show.

If I build again, I just get redirected to the (empty) Build Images list (since the Image was already built).

**Comment by jkuri** [comment]
Hi @ComiR. thank you for your report and helping us make `abstruse` better.
I also noticed in some cases that image that has just being built is not showing in the image list.
It looks like image doesn't get written to the database.
It would be really helpful if you can check if the image and correlated files were stored in the abstruse config directory:

```sh
-rw-r--r--   1 jan  staff  106496 Oct 18 19:22 abstruse.sqlite
drwxr-xr-x   3 jan  staff      96 Oct 18 19:16 avatars
drwxr-xr-x   3 jan  staff      96 Oct 18 19:18 cache
-rw-r--r--   1 jan  staff     467 Oct 18 19:17 config.json
drwxr-xr-x  11 jan  staff     352 Oct 18 19:16 docker-essential
drwxr-xr-x   2 jan  staff      64 Oct 18 17:21 images
-rw-r--r--   1 jan  staff    3243 Oct 18 17:21 rsa.key
-rw-r--r--   1 jan  staff     814 Oct 18 17:21 rsa.pub
```

image should be under `images/` folder. Can you please check so we can fix that asap? thanks!
