### ISSUE TITLE
Bitbucket repositories not appearing after push

### ISSUE THREAD

**Issue by staticn0de** [bleenco/abstruse#315]
Hi all,

I'm having difficulty getting bitbucket to integrate with abstruse. 

Within bitbucket, I've configured my webhook with the url below. This works and I see a http 200 return in bitucket. 

> http://192.168.0.240:6500/webhook/bitbucket

When I push to the repo, bitbucket says it was successful. Looking at the abstruse logs I see nothing to indicate that it is communicating with bitbucket. 

Webhook request contains:
**# Request details**
Event type:repo:refs_changed
URL endpoint:http://192.168.0.240:6500/webhook/bitbucket

**Headers**
`X-Hub-Signature: sha256=c6abccd16026ab4069c10a83f2dce5e302189171bf1faeb618ed7c8296ed39f5
X-Request-Id: 597d329d-93ba-4a6b-94ae-e5508b06fb86
Content-Type: application/json; charset=utf-8
X-Event-Key: repo:refs_changed`

**Body**
`{"eventKey":"repo:refs_changed","date":"2017-12-14T07:04:19+0000","actor":{"name":"admin","emailAddress":"user@example.com","id":1,"displayName":"John Doe","active":true,"slug":"admin","type":"NORMAL"},"repository":{"slug":"test-repo","id":22,"name":"test-repo","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"UT","id":1,"name":"Unity Tutorials","description":"This is my Unity 3D tutorials project.","public":false,"type":"NORMAL"},"public":false},"changes":[{"ref":{"id":"refs/heads/master","displayId":"master","type":"BRANCH"},"refId":"refs/heads/master","fromHash":"fd8e7566c9997d6d75bef0eb5884c7c0aa10ce84","toHash":"5d9fc79f1bc56b181a74cc824d1f6dec04a04e70","type":"UPDATE"}]}
`

**# Response details**
HTTP status:200
Duration44ms

**Headers**
`ETag: W/"227-16044ff1d10"
X-Powered-By: Express
Cache-Control: public, max-age=0
Access-Control-Allow-Origin: *
Last-Modified: Mon, 11 Dec 2017 09:54:18 GMT
Accept-Ranges: bytes
Content-Length: 551
Date: Thu, 14 Dec 2017 07:04:20 GMT
Content-Type: text/html; charset=UTF-8
Via: 1.1 localhost (Apache-HttpClient/4.4.1 (cache))
Connection: keep-alive`

**Body**
`<!DOCTYPE html> <html> <head> <meta charset="utf-8"> <title>Abstruse CI</title> <base href="/"> <meta name="viewport" content="width=device-width,initial-scale=1"> <link id="favicon" rel="icon" type="image/x-icon" href="images/favicon.png"> <link href="css/9f9f258f3b43fee91e64.css" rel="stylesheet"></head> <body> <app-root></app-root> <script type="text/javascript" src="js/polyfills.bundle.js"></script><script type="text/javascript" src="js/styles.bundle.js"></script><script type="text/javascript" src="js/app.bundle.js"></script></body> </html> 
`

Any idea why it won't appear in Abstruse?

**Comment by jkuri** [comment]
hi @staticn0de!

did you set up your access token under you settings:

![screen shot 2017-12-15 at 08 05 33](https://user-images.githubusercontent.com/1796022/34030828-e4a80d86-e16e-11e7-9ad1-1839cd01560f.png)

when this is configured you need to apply access token on repository settings:

![screen shot 2017-12-15 at 08 05 51](https://user-images.githubusercontent.com/1796022/34030845-f9d5fa74-e16e-11e7-809d-83417c6b8a50.png)

**Comment by jkuri** [comment]
also, please make sure your repository includes `.abstruse.yml` file, you can if everything is okay with your repository in `repository settings`.

**Comment by Izak88** [comment]
You have to send a request to `http://192.168.0.240:6500/webhooks/bitbucket`, you're missing `s` in `webhooks`, that's probably the reason why nothing appears in Abstruse...

**Comment by staticn0de** [comment]
Cheers @Izak88, I noticed that just after I posted it. When I added the s it changed it to a http400 error in bitbucket. 

I didn't have the access token but it's in now. 

I'm seeing this new response within bitbucket 

Response details
HTTP status:400

**Headers**
`Access-Control-Allow-Origin: *
ETag: W/"2e-2zFLBLWaIlEQV90ZfTIiIqZlMyk"
Connection: keep-alive
Content-Length: 46
Date: Fri, 15 Dec 2017 07:28:06 GMT
X-Powered-By: Express
Via: 1.1 localhost (Apache-HttpClient/4.4.1 (cache))
Content-Type: application/json; charset=UTF-8`

**Body**
`{"error":"No X-Request-UUID found on request"}`

I see http400 on http://abstruse:6500/webhooks/bitbucket and http://abstruse:6500/webhooks/github and http200 on http://abstruse:6500/webhooks/

**Comment by Izak88** [comment]
Yes, in the header the following fields are required:
- x-request-uuid represents id of a request
- x-event-key represents event type
- x-hook-uuid represents id of user

If you want, you can take a look our examples of bitbucket webhooks in repository (`tests/e2e/webhooks/bitbucket`) in each example there is a request and a header...
