### ISSUE TITLE
[feature] Logging

### ISSUE THREAD

**Issue by mmaldacker** [bleenco/abstruse#322]
Hi

It would be nice to have access to the entire logs of a build, it seems currently there is a limit to how much is kept (can't scroll further after a while). It would be also nice if the logs could be downloaded. 

Same for the logs of an image build.

Thanks!

**Comment by jkuri** [comment]
hi @mmaldacker. I will implement viewing raw logs during the weekend.
About scroll blocking when viewing logs, can you please clarify when does that happen, because I cannot reproduce it. There's no limit currently how much lines can be included. thanks!

**Comment by mmaldacker** [comment]
E.g. this build: http://vortex2d.strangled.net:6500/job/83 I can't see the cmake logs & build logs, only part of the unit-tests output.

**Comment by jkuri** [comment]
okay I see. I'll try to reproduce this locally and make a fix. Hopefully there's not some limitation with the `sqlite3`. 

btw, there's no need to access abstruse via port 6500. You can set proxy server (nginx for example) to this port or configure port to 80 in `config.json` at abstruse config directory in case this is only web service you are running on the server. 
Your config file should look something like:
```json
{
  "url": "http://vortex2d.strangled.net",
  "secret": "thisIsSecret",
  "jwtSecret": "abstruseSecret4321!!",
  "port": 80,
  "concurrency": 10,
  "idleTimeout": 600,
  "jobTimeout": 3600,
  "ssl": false,
  "sslcert": null,
  "sslkey": null,
  "publicKey": "rsa.pub",
  "privateKey": "rsa.key",
  "requireLogin": false,
  "demo": false,
  "db": {
    "client": "sqlite3",
    "connection": {
      "filename": "./abstruse.sqlite"
    },
    "useNullAsDefault": true
  }
}
```

Additionaly, I would reccomend you to set up https certs for abstruse. They are free, you just need to generate it with https://letsencrypt.org/.

Cheers, Jan

**Comment by mmaldacker** [comment]
Oh I didn't realise you could set it up with https. Thanks!
