### ISSUE TITLE
[question]: adding repositories // RESOLVED

### ISSUE THREAD

**Issue by roens** [bleenco/abstruse#332]
I'm very intrigued by Abstruse. However, it's entirely unclear how to add any repository to it. I've been poking at it for a few hours, running the latest docker image (v1.4.4). I've gone poking around in the `/root/.abstruse/config.json` file, and the web UI (after creating an admin user account). Nowhere is it apparent how to add a repo. (Specifically, I'm interested in using it with our existing GitLab service.)

Thanks in advance!

**Comment by jkuri** [comment]
hi @roens. Repository is automatically added as soon as you add webhooks or is initial webhook triggered. not sure about GitLab but when you add webhook url at GitHub it triggers init webhook request. I guess its pretty similar with GitLab. Hope this helps, if you have any further question do not hesitate to ask!

**Comment by roens** [comment]
Hey, thanks for the speedy reply!

I see. I gather that in order to test things, I'll have to se up Abstruse somewhere our GitLab host can reach it, rather than on my laptop on a NAT'd office network.

**Comment by jkuri** [comment]
speedy reply from a man on speed :) 

yes, that's correct. to get an idea how builds work you can run one of the scripts placed [here](https://github.com/bleenco/abstruse/tree/master/tests/dev-scripts), for example: `node tests/dev-scripts/push-d3.js`. That should run test build on your laptop. Please make sure that you first builded docker image with name `abstruse` so test build can find it. I also recorded some screen sharing [here](https://www.youtube.com/watch?v=xmizxTGk92k) with the whole initial process.

**Comment by irmana** [comment]
If I can add to this topic, @roens would you mind sharing some thoughts with us after you try abstruse out? Thanks.

**Comment by roens** [comment]
I'd be happy to, @irmana. I'm particularly interested in Abstruse for replacing Jenkins, while remaining being a CI tool that lives within our infrastructure. After I've had a chance to set it up & try it out I'll loop back here to let you know how it went.

The quick & helpful responsiveness I've had on this issue alone has been a positive experience so far!

**Comment by roens** [comment]
Alright. I've now got Abstruse running in docker on a machine within our infrastructure. I've set `secret` in `~/.abstruse/config.json`. But I'm uncertain how to format the webhook URL, when setting that up in GitLab. From the [screenshot](https://github.com/bleenco/abstruse/blob/master/docs/INTEGRATING_GIT_PROVIDERS.md#2-setting-up-github-webhooks), it looks like it might be something like:
* `http://hostname:6500/webhooks/gitlab` (replacing `hostname` with the actual, resolvable hostname of the server)

.. but that URL seems to just redirect to `app-root`:
```
<!DOCTYPE html> 
<html> 
  <head>
    <meta charset="utf-8"> <title>Abstruse CI</title>
    <base href="/">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link id="favicon" rel="icon" type="image/x-icon" href="images/favicon.png">
    <link href="css/b5e38590e147b7722061.css" rel="stylesheet">
  </head>
  <body>
    <app-root></app-root>
    <script type="text/javascript" src="js/polyfills.bundle.js"></script>
    <script type="text/javascript" src="js/styles.bundle.js"></script>
    <script type="text/javascript" src="js/app.bundle.js"></script>
  </body>
</html>
```
----
It would be useful to have indication (by text, rather than just screenshot) of the webhook endpoints that Abstruse watches for.

**Comment by jkuri** [comment]
I believe you are hitting `/webhooks/gitlab` url from browser with `GET` request.
`/webhooks/*` urls only works with `POST` HTTP requests.
If you want to trigger that manually use tool like `curl -X POST`. [Here](https://github.com/bleenco/abstruse/blob/master/tests/e2e/webhooks/gitlab/PushEvents.ts) is example of http request body and at the bottom request headers that should be present.

**Comment by jkuri** [comment]
the easiest way then triggering manual build would be to go to:
```
Repositories -> Repository -> Settings
```
and you'll see at the bottom:
![screen shot 2018-01-10 at 04 06 52](https://user-images.githubusercontent.com/1796022/34754061-df7092e6-f5bb-11e7-9493-f9e36c6b46a7.png)
Click on the `Fetch Config` then you can manually change the config and trigger test build.

**Comment by roens** [comment]
Ok, 🤦‍♂️ …

I did, indeed, guess/use the correct webhook URL: `http://hostname:6500/webhooks/gitlab`.

The problem was a firewall issue. The attempts at hitting that from GitLab were just timing out. I got one to succeed after firewall edits, and now have one repo showing in Abstruse!

Now to proceed with seeing what I can get set up.

**Comment by jkuri** [comment]
@roens did you manage things out? let me know if you need additional input.

**Comment by irmana** [comment]
This issue is considered resolved, @roens please reopen when this is still an issue.
