### ISSUE TITLE
abstruse_builder fails to build

### ISSUE THREAD

**Issue by chriscowley** [bleenco/abstruse#334]
Run `docker build` and copying `fluxbox` to `/etc/init.d` fails:

After it initially failed in the GUI, I took the Dockerfile it outputs a built it on the CLI to ensure it was not simply a timeout because my connection is not the best, but it genuinely does fail.

Dockerfile used:

```
FROM ubuntu:17.10

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:99

# please do not edit between lines or image on abstruse will not work properly

# -------------------------------------------------------------------------------------------

RUN set -xe \
    && apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates curl build-essential \
    && apt-get install -y --no-install-recommends libssl-dev git python \
    && apt-get install -y --no-install-recommends sudo \
    && apt-get install -y --no-install-recommends xvfb x11vnc fluxbox xterm openssh-server

RUN useradd -u 1000 -g 100 -G sudo --shell /bin/bash -m --home-dir /home/abstruse abstruse \
    && echo 'abstruse ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers \
    && echo 'abstruse:abstrusePass' | chpasswd

COPY fluxbox /etc/init.d/
COPY x11vnc /etc/init.d/
COPY xvfb /etc/init.d/
COPY entry.sh /

```

[Build log](https://gist.github.com/chriscowley/b7a576102bcda791b945740162c1686c)

**Comment by chriscowley** [comment]
Forget it, I was being special - however, it could do with a longer timeout to deal with people one rural french ADSL connections

**Comment by jkuri** [comment]
@chriscowley what timeout do you mean? can you clarify please so we can fix this?

**Comment by chriscowley** [comment]
Building the image took a long time because my internet is rubbish. Eventually it just gave up.

**Comment by jkuri** [comment]
okay. glad you finally made it work. fyi in the cases when my internet is rubbish I just switch to LTE :)

**Comment by chriscowley** [comment]
I live in rural Brittany - if my phone manages 2G in the house I am happy
