### ISSUE TITLE
Removal of built docker 'build' images removes custom image definitions from UI.

### ISSUE THREAD

**Issue by cooperaj** [bleenco/abstruse#347]
Using bleenco/abstuse:latest as of about 30 minutes ago.

I found that my go builds weren't working. In an effort to remove any complications related to stale build images I deleted the two of them (abstruse_builder and my custom go_builder)

I clicked the 'abstruse_builder' edit button and rebuilt the image. Upon returning to the images page I found that the 'go_builder' custom image had disappeared from the configuration options.

I've lost all the docker file content (and init file) that I'd entered.

**Comment by jkuri** [comment]
please check if there is still something in `~/.abstruse/images`.

**Comment by cooperaj** [comment]
Yep. Folder (with files) exists in there for go_builder.

I've duplicated out the contents now so haven't lost them.

**Comment by jkuri** [comment]
great, glad to hear that.

bug is still very relevant and relates to UI implementation of building images. should be refactored.
