### ISSUE TITLE
Can't integrate with bitbucket cloud.

### ISSUE THREAD

**Issue by dedkat** [bleenco/abstruse#348]
Hi, 
I've private repos on bitbucket and I'm trying to integrate it into abstruse. I'm not sure which access token should I use to get access to my repository - I'm trying with "App passwords" because  there's no such thing as Access Token on Bitbucket.

Adding GitHub repos works fine.

logs from container when I'm trying to check configuration:
```
(node:7) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at validateHeader (_http_outgoing.js:503:11)
    at ServerResponse.setHeader (_http_outgoing.js:510:3)
    at ServerResponse.j.set.j.header (/app/dist/api/index.js:2:1655556)
    at ServerResponse.j.json (/app/dist/api/index.js:2:1652430)
    at h.getRepository.then.then.then.then.catch.e (/app/dist/api/index.js:2:1743046)
    at <anonymous>
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
```

**Comment by jkuri** [comment]
hi @dedkat, thanks for report. I will check this right off.

**Comment by jkuri** [comment]
I am investigating on that and found tutorial how to setup access token [here](https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html). I created BitBucket account but cannot find that option under my profile settings. 
I believe "App Passwords" is not the same thing as `Access Token` since git clone is performed as 
`git clone https://[access-token]@provider.com/username/repository.git` and cannot get that working with `App Passwords` settings under BitBucket.
I will investigate this further, please let me know if you figure it out something in the meanwhile.
Maybe Access Tokens option is only available on BitBucket with paid account?

**Comment by dedkat** [comment]
Hi,
This tutorial is for Bitbucket Server not Bitbucket Cloud. There's no hidden options in Bitbucket. Other CI system (like Concourse, Drone) use for integration OAuth Key and Secret (ACCESS MANAGEMENT -> OAuth -> OAuth consumers).

**Comment by dedkat** [comment]
Ok, so what happens whit this issue?

**Comment by jkuri** [comment]
@dedkat it is high on my priority list, hopefully I will make it done till end of the week.

**Comment by jkuri** [comment]
@dedkat check https://github.com/bleenco/abstruse/pull/371 if you have time please

**Comment by jkuri** [comment]
resolved with https://github.com/bleenco/abstruse/pull/371

**Comment by dedkat** [comment]
Nothing changed for me :/

**Comment by jkuri** [comment]
you need to update to `1.6.0` version for bitbucket cloud integration to work.

**Comment by jkuri** [comment]
I just noticed there is some issue with production build, give me a couple of minutes.

**Comment by jkuri** [comment]
sorry about that @dedkat, it was working for me in development mode but UI breaked in production build and I was not cautious about that.
I created https://github.com/bleenco/abstruse/pull/373, after CI passes I will immediately release `1.6.1`. Then you will have new form:

![screen shot 2018-05-07 at 15 47 05](https://user-images.githubusercontent.com/1796022/39705350-71a35c12-520e-11e8-9b1b-e177b4d5394d.png)

You then need to apply this credentials to repository under repository -> settings and it should work right off.

Btw, I added extra fields in database for table `access_token`, the fastest way to override this is to delete old database `abstruse.sqlite` so the new one is created.

**Comment by dedkat** [comment]
Thanks :)
There's small mistake in docker run command, configuration folder is in /root/abstruse not /root/.abstruse

**Comment by jkuri** [comment]
thanks, I'll fix it right away.

**Comment by jkuri** [comment]
@dedkat `1.6.1` released on docker cloud.. please let me know if some issues still persist.

**Comment by dedkat** [comment]
What's "Bitbucket Client ID"? I can't find it in OAuth section in Bitbucket. I've tried name of OAuth consumer but it's not working.

**Comment by jkuri** [comment]
It's your Bitbucket username.

**Comment by technic** [comment]
Hi, what do I need to set as "Callback URL" in the bitbucket cloud OAuth settings?

**Comment by dedkat** [comment]
It's probably your abstruse URL

**Comment by dedkat** [comment]
There's another problem, bitbucket webhook triggers builds of all repos on abstruse.

**Comment by technic** [comment]
Ok. I managed to set it up, but it crashes.
url is your.abstruse.server/webhooks/bitbucket

**Comment by dedkat** [comment]
@technic it works for me, it crashes only when I trigger test build in repo settings.

**Comment by jkuri** [comment]
@dedkat can you please paste me error from console, I'll take a look later and fix test builds from repository settings for bitbucker configurations.

**Comment by dedkat** [comment]
@jkuri thanks :)

> node:7) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
> [2018-06-13 17:56:41]: [server]: starting Abstruse CI version 1.6.3 ...
> [2018-06-13 17:56:41]: [server]: API and Socket Server running at port 6500
> [2018-06-13 17:56:42]: [socket]: user dedkat@dedkat.net connected from ::ffff:37.47.164.79
> undefined:1
> 
> 
> 
> SyntaxError: Unexpected end of JSON input
>     at JSON.parse (<anonymous>)
>     at U.o [as _callback] (/app/dist/api/index.js:40:152641)
>     at U.t._callback.t.callback.t.callback (/app/dist/api/index.js:588:3090)
>     at U.emit (events.js:182:13)
>     at U.<anonymous> (/app/dist/api/index.js:588:15765)
>     at U.emit (events.js:182:13)
>     at IncomingMessage.<anonymous> (/app/dist/api/index.js:588:14607)
>     at Object.onceWrapper (events.js:273:13)
>     at IncomingMessage.emit (events.js:187:15)
>     at endReadableNT (_stream_readable.js:1081:12)
>     at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by martin-juul** [comment]
Sam

> @jkuri thanks :)
> 
> ...

Same issue. Abstruse lists the repo in the ui, so it does authenticate. When i trigger a test build, i get the same error though.

```
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at U.o [as _callback] (/app/dist/api/index.js:40:117106)
    at U.t._callback.t.callback.t.callback (/app/dist/api/index.js:586:3089)
    at U.emit (events.js:182:13)
    at U.<anonymous> (/app/dist/api/index.js:586:15779)
    at U.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/app/dist/api/index.js:586:14621)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
