### ISSUE TITLE
[bug]: terminal fonts in Linux

### ISSUE THREAD

**Issue by ad-m** [bleenco/abstruse#362]
I visited https://ci.bleenco.io/job/5413 . The font of logs looks terrible:
![zaznaczenie_1447](https://user-images.githubusercontent.com/3618479/38658669-6421fbee-3e26-11e8-888e-caf862333905.png)

Firefox 60.0b10 (64 bity) on Ubuntu 16.04

**Comment by jkuri** [comment]
thanks for the report. yes, this look nasty ;) I will fix it today.
