### ISSUE TITLE
[security] Don't use default secrets

### ISSUE THREAD

**Issue by captn3m0** [bleenco/abstruse#363]
The homepage for abstruse gives a one liner to install which leaves your setup in a very vulnerable state because both your JWT secret as well as your webhook secrets are set to default values.

The first lets anyone spoof themselves as the admin user, and the second lets anyone initiate a build.

[The installation guide](https://github.com/bleenco/abstruse/blob/master/docs/INSTALLATION.md) does not mention the default secret anywhere.

**Comment by jkuri** [comment]
@captn3m0 thanks for a nice warning. you are totally right about that, since I am more or less only developer on this project cannot think of all the things possible. fixing that right away.

**Comment by captn3m0** [comment]
I'd suggest:

1. Using environment variables as configuration parameters to accept `JWT_SECRET` and `WEBHOOK_SECRET`
2. Refusing to run if either of these are set to empty or default values.
3. Pushing out a release with empty values in the default configuration file with a security notice so that everyone affected gets a new JWT Secret by default.

Maybe allowing config file as a volume mount in the default installation? Just provide a sample file with empty values that users must mount?

**Comment by jkuri** [comment]
first part about changing secrets on demo site ... done.

1. I would really keep this configuration inside `config.json` but stated clearly in the README that this is mandatory to change, I would prefer having second step of initial setup setting this values via web UI. This is not a lot of work and I can acomplish this in about an hour.
2. The web UI setup would not let you proceed until you change or update secrets.
3. Yes, with empty initial values in the `config.json`, that would be another indicator that setup has not been done yet and won't let you run application.

About mouting image to docker container it is already in the installation steps:
```
 -v ~/abstruse:/root/.abstruse
```

As stated above I will add myself points here to acomplish, please add comment if anything missing or any corrections are needed;

- [ ] init `config.json` with empty values
- [ ] add additional step in init setup UI to set `jwt` and `webhook_secret`
- [ ] make sure fields are filled before letting proceed the setup
- [ ] make sure secrets are complex enough (maybe checking length and at least one number is enough)

**Comment by captn3m0** [comment]
>add additional step in init setup UI to set jwt and webhook_secret

I'd sent a suggestion for this over email, but posting here as well:

>As an alternative to checking complexity and asking user for values, it might be easier and better to just generate 2 random tokens on setup.

Since these values are configured at first boot, it might be much more saner to just generate random values for both on system boot (and regenerate if a default/empty value is found as well)
