### ISSUE TITLE
[feat] Support Gitea Webhooks

### ISSUE THREAD

**Issue by captn3m0** [bleenco/abstruse#365]
The headers are slightly different compared to other providers. They fake `X-GitHub-*` headers as well, but GitHub seems to be using `X-Hub-*`

```
Request URL: https://ci.bb8.fun/webhooks/github
Request method: POST
Content-Type: application/json
X-GitHub-Delivery: 858d7102-3854-4d7c-a9f5-38ce7f91a000
X-GitHub-Event: push
X-Gitea-Delivery: 858d7102-3854-4d7c-a9f5-38ce7f91a000
X-Gitea-Event: push
X-Gogs-Delivery: 858d7102-3854-4d7c-a9f5-38ce7f91a000
X-Gogs-Event: push
```

Gitea is https://gitea.io, a fork of gogs.

**Comment by captn3m0** [comment]
Looked into it a bit more, gitea sends the secret in the request payload instead of using HMAC like GitHub does.

I've filed a issue on gitea to use HMAC: https://github.com/go-gitea/gitea/issues/3901

But it would be nice if abstruse supported gitea natively (by reading the `secret` field in the request)

**Comment by jkuri** [comment]
thanks! it is in plan tu support gitea natively till the next release.

**Comment by Neirda24** [comment]
Hi ! That would be very nice as I plan to use gitea + abstruse ;). @jkuri : do you have a roadmap or anything for us to follow this request ?

Thanks.

**Comment by jkuri** [comment]
hi @Neirda24! there's no roadmap currently only local branch on my computer :)

**Comment by irmana** [comment]
@Neirda24 and @captn3m0 
When you are still interested into this feature we will include it in `2.0` release that will go out soon. Please let us know asap so we can squeeze it in. ;)

**Comment by huafu** [comment]
@irmana  I don't know about them, but I'd personally love to have my gitea be able to talk to abstruse ;-)

**Comment by AragurDEV** [comment]
Hi all, is there any update for Gitea integration?
