### ISSUE TITLE
Cant get Bitbucket WebHook working

### ISSUE THREAD

**Issue by port22** [bleenco/abstruse#370]
Hey,

while abstruse seems absolutely what I was looking for, unfortunately I can't get it to start anything after BitBucket seemed to have triggered a webhook.

Host: CoreOS with Bitbucket and Abstruse on Docker

Within Abstruse I built the initial example abstruse_builder image named "abstruse" and placed a `.abstruse.yml` in the repo root with the following content:

```
image: abstruse
script:
  - docker build -t testimage .
```

I changed the secrets in the config.yml to just "abstruse" and also created an Access Token valued "abstruse", just for testing if it works.

Then I added a BitBucket Webhook with URL (test replys with 200) and the "abstruse" secret.
After git push, the Bitbucket sais "Just Now" on last success but at abstruse-side nothing happens and nothing in the logs.

The BitBucket request looks like:
```
X-Hub-Signature: sha256=a5f23432727cafrd64da923474abdd29e09b0158fb5f72fe21d9d9ea4d0ff145
X-Request-Id: 58a7a497-b56f-4b27-af95-1816dcfa8c93
Content-Type: application/json; charset=utf-8
X-Event-Key: repo:refs_changed

{"eventKey":"repo:refs_changed","date":"2018-04-29T15:32:10+0000","actor":{"name":"myname","emailAddress":"my@email.com","id":18,"displayName":"My Name","active":true,"slug":"myuser","type":"NORMAL"},"repository":{"slug":"testrepo","id":12,"name":"restrepo","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":true,"project":{"key":"DOC","id":82,"name":"docker","description":"Docker Image Builds","public":false,"type":"NORMAL"},"public":true},"changes":[{"ref":{"id":"refs/heads/master","displayId":"master","type":"BRANCH"},"refId":"refs/heads/master","fromHash":"4a6c2928cb9113220fb72crfcf4305f5c3b74699","toHash":"b3b7d3edc29c9a20d1d6ar6f726eba8016dc5d6e","type":"UPDATE"}]}
```

Can you point me on where I am something missing please? Thanks a lot!

**Comment by jkuri** [comment]
Hi, you are not missing anything but Bitbucket unfortunatelly doesn't support access tokens as other providers do and we still didn't integrate oauth to work with Bitbucket. It is high on our priority list and you can expect some progress on that if not done in a couple of days. 
Related: https://github.com/bleenco/abstruse/issues/348

**Comment by jkuri** [comment]
@port22 #371 ready

**Comment by port22** [comment]
fabulous !
