### ISSUE TITLE
Permissions for Gitlab

### ISSUE THREAD

**Issue by quatermain** [bleenco/abstruse#374]
I have this docker compose settings:
```
version: "2"

services:
  abstruse:
    image: "bleenco/abstruse:v1.6.1"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/abstruse-config:/root/.abstruse"
    ports:
      - '80:6500'
```

and we use GitLab. So I created personal token (I'm admin):
![screen shot 2018-05-07 at 17 02 25](https://user-images.githubusercontent.com/1125806/39708809-6f3a2848-5218-11e8-9f09-84de10766c49.png)

I created WebHook in GItLab and it created repository in Abstruse. I added my token and pair it with repository.
![screen shot 2018-05-07 at 17 03 18](https://user-images.githubusercontent.com/1125806/39708904-b492358e-5218-11e8-844f-dee7988cf5c6.png)

But I still get error with permissions:
![screen shot 2018-05-07 at 17 02 40](https://user-images.githubusercontent.com/1125806/39708932-c72c879e-5218-11e8-9122-c4aa340eb74b.png)

Error from console:
```
abstruse_1  | (node:7) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
abstruse_1  |     at validateHeader (_http_outgoing.js:503:11)
abstruse_1  |     at ServerResponse.setHeader (_http_outgoing.js:510:3)
abstruse_1  |     at ServerResponse.j.set.j.header (/app/dist/api/index.js:562:6343)
abstruse_1  |     at ServerResponse.j.json (/app/dist/api/index.js:562:3217)
abstruse_1  |     at h.getRepository.then.then.then.then.then.catch.e (/app/dist/api/index.js:574:80009)
abstruse_1  |     at <anonymous>
abstruse_1  | (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 8)
abstruse_1  | (node:7) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
abstruse_1  |     at validateHeader (_http_outgoing.js:503:11)
abstruse_1  |     at ServerResponse.setHeader (_http_outgoing.js:510:3)
abstruse_1  |     at ServerResponse.j.set.j.header (/app/dist/api/index.js:562:6343)
abstruse_1  |     at ServerResponse.j.json (/app/dist/api/index.js:562:3217)
abstruse_1  |     at h.getRepository.then.then.then.then.then.catch.e (/app/dist/api/index.js:574:80009)
abstruse_1  |     at <anonymous>
abstruse_1  | (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
```

**Comment by jkuri** [comment]
hi @quatermain! seems like you configured eveything right. Can you please try to trigger some test build via git and let me know the result. This might only be issue with "configuration check", which of course still need to be resolved.

**Comment by jkuri** [comment]
Another note, documentation was not updated, please set
```
- "~/abstruse-config:/root/abstruse"
```
insted of
```
- "~/abstruse-config:/root/.abstruse"
```

in your docker compose.

**Comment by quatermain** [comment]
Thanks, let me know if I can help you with it. I will be offline for 2 hours but after that I can help you with something.

**Comment by quatermain** [comment]
btw: It's issue with https://gitlab.com/, not on-premise version.

**Comment by jkuri** [comment]
okay thanks, I will create an account and check there as well.

**Comment by jkuri** [comment]
I installed GitLab locally and figured out where is the issue, if you want to clone from GitLab with access token you need to do it
as `git clone https://username:access_token@gitlab.com/user/repository.git` but Abstruse is using GitHub approach here with just `git clone https://access_token@gitlab.com/user/repository.git` so that's why `128` git error.

I will come up with the fix in the next couple of hours.

- [ ] add additional field in the UI for GitLab configuration to enter username and save this to db
- [ ] check if repository has `gitlab_id` defined and use `username:access_token` authentication strategy for cloning repositories
- [ ] do not hardcode `gitlab.com` domain in `commit-status.ts` but use hostname where webhook is tiggered from as `http(s)://hostname/api/v4/projects/${id}/statuses/${sha}` for sending build statuses

**Comment by jkuri** [comment]
@quatermain if you have time please check https://github.com/bleenco/abstruse/pull/375 if it works with gitlab.com. 

1. Delete `abstruse.sqlite` so new one is created or `alter table access_tokens add gitlab_username varchar(255);` 
2. clone repository: `git clone https://github.com/bleenco/abstruse.git`
3. fetch PR `git fetch origin pull/375/head:pr375`
4. checkout to PR `git checkout pr375`
5. Build image: `npm run build-image`
6. run image that you have just built
6. Add new access token via web UI, you should have new username option for Gitlab
![screen shot 2018-05-07 at 22 39 37](https://user-images.githubusercontent.com/1796022/39723915-8e6201f8-5247-11e8-885c-57e75a9fc3e6.png)
7. Go to repository settings and use that token, then try to trigger test build

Please let me know if it works, I checked with local gitlab installation and it does. Thank you.

**Comment by jkuri** [comment]
I checked myself and it works, you just need to be sure you mark all scopes when generating access token on GitLab:
![screen shot 2018-05-07 at 23 42 49](https://user-images.githubusercontent.com/1796022/39726780-8124726a-5250-11e8-8d58-b8b13dbcde67.png)

then it should work:

![screen shot 2018-05-07 at 23 44 20](https://user-images.githubusercontent.com/1796022/39726798-97d431c6-5250-11e8-8c07-3ee4f1285cc7.png)

thank your for the nice report and help!

**Comment by quatermain** [comment]
it still show error around "Check Configuration" and but it get config file, but build is still 00:00 and it doesn't build our images. I think we are going to move from GitLab to GitHub.

**Comment by jkuri** [comment]
what does it says for build, is there any log? did you go to `repository settings => access token` and set the correct authentication that you saved under user settings?

**Comment by quatermain** [comment]
yes, I did all things and still that issue. We just left gitlab so let me know if you want to help from me and I can try something else again on our old repository on gitlab

--
Oliver Kriška
+421 908 841 243
