### ISSUE TITLE
[Question] Deployment to filesystem?

### ISSUE THREAD

**Issue by domiSchenk** [bleenco/abstruse#376]
I'm struggling to deploy my angular app.

How are commands defined?
How can i copy the dist folder to a specific folder on the host system?

thanks

**Comment by domiSchenk** [comment]
So i have to define my script like this?
```
deploy:
  - ./deploy.sh
```

And in which context will this script run? (which container)

**Comment by jkuri** [comment]
I am not a deployment expert, but I guess you want to deploy only tags or when merged to master, not pull requests for sure. Check [here](https://github.com/bleenco/abstruse/blob/master/docs/ENV_VARIABLES.md) which variables are globally defined.
You may also want to check before that tests are passing before executing deployment script.
About container, you define your own image as `image: your_image_name` in `.abstruse.yml` configuration.

**Comment by jkuri** [comment]
@domiSchenk you got this resolved?

**Comment by domiSchenk** [comment]
Not really, but I'm not sure if it is possible what i want to do with abstruse.

so we can close this one.
