### ISSUE TITLE
How to save exit code in variable when running scripts?

### ISSUE THREAD

**Issue by marcopiraccini** [bleenco/abstruse#379]
Hi, 

A Question. I have to run some tests, then passing the exit code of `npm test` to another script, something like:

```
script:
  - npm run test; export TEST_RESULT=$?
  - echo $TEST_RESULT
```

...but apparently, this doesn't work...there's a way to do this?

**Comment by marcopiraccini** [comment]
OK, found in doc, I can use `ABSTRUSE_TEST_RESULT`

**Comment by irmana** [comment]
@marcopiraccini we would appreciate when you would close this issue in case it's resolved. Thx
