### ISSUE TITLE
[enhancement] Additional secrets in configuration

### ISSUE THREAD

**Issue by dedkat** [bleenco/abstruse#381]
Is there a chance to add functionality to keep additional secrets/access tokens (as variables) in settings and use them in builds?

**Comment by jkuri** [comment]
sure, you mean environment variables. go to repository settings and set them on this form:

![screen shot 2018-06-08 at 14 06 41](https://user-images.githubusercontent.com/1796022/41157237-4a9caa9e-6b25-11e8-8b9d-6a1664f814d8.png)

as you can see you can also encrypt them if they include sensitive data such as access token.
Btw, this is also described [here](https://github.com/bleenco/abstruse/blob/master/docs/ENV_VARIABLES.md), seems like you missed it.

**Comment by dedkat** [comment]
Sorry, my bad. I've seen that but forgot it :)

**Comment by jkuri** [comment]
no problem :) please close the issue if this solves your problem.
