### ISSUE TITLE
Dashboard showing wrong memory consumption

### ISSUE THREAD

**Issue by douglasmiranda** [bleenco/abstruse#383]
I see this in the dashboard:

<img width="368" alt="screen shot 2018-06-13 at 15 58 49" src="https://user-images.githubusercontent.com/542013/41375579-82f0cab2-6f24-11e8-9df7-0359ea11e1ed.png">

But I just started abstruse, and the real consumption is (`htop`):

<img width="1077" alt="screen shot 2018-06-13 at 15 57 42" src="https://user-images.githubusercontent.com/542013/41375598-8d235824-6f24-11e8-81af-b9fad076b544.png">

`docker stats`

```
CONTAINER ID        NAME                CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
4914c6563a1a        clever_fermat       0.46%               39.66MiB / 996.5MiB   3.98%               168kB / 3.18MB      131kB / 201kB       11
898fec2c5e7d        angry_swirles       0.00%               39.09MiB / 996.5MiB   3.92%               1.22kB / 0B         2.31MB / 328kB      11
```
---
I'm using the latest abstruse:

```
REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE
bleenco/abstruse           latest              bf1cd9462cb5        4 days ago          234MB
```

Run command:
```
docker run -dit -v /var/run/docker.sock:/var/run/docker.sock -v ~/abstruse:/root/abstruse -p 6500:6500 bleenco/abstruse
```
**Output of `docker info`:**
<details>
  <summary>Click to expand</summary>

```
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 21
Server Version: 18.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-6-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.5MiB
Name: devtools-debian-s-1vcpu-1gb-nyc3-01
ID: TPO5:KDCP:IEXD:KSZK:GTDA:H65C:KMUG:W2DE:WOLZ:OSKM:5W63:WNM5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```
</details>

---
The host is a Digital Ocean Debian Stretch droplet.
```
Linux devtools-debian-s-1vcpu-1gb-nyc3-01 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
```

**Comment by jkuri** [comment]
hello @douglasmiranda and thanks for this report.
that is very interesting, if you check [here](https://github.com/bleenco/abstruse/blob/master/src/api/stats/memory.ts), `abstruse` is using Node.JS method [os.freemem()](https://nodejs.org/api/os.html#os_os_freemem) for fetching free  memory values. if you exec `free -m`, do you get same values?
maybe `freemem()` returns memory that is not allocated nevertheless it is used or not. I think used and allocated memory are not the same things. 
not sure what we can do here to improve this stats, do you have any suggestions?

**Comment by douglasmiranda** [comment]
`free -m` returned:

```
              total        used        free      shared  buff/cache   available
Mem:            996         161         151          12         683         670
Swap:             0           0           0
```

..and the dashboard stays the same. =/

I'll try to investigate a little more.

**Comment by jkuri** [comment]
Then it is correct, `free -m` returned that `151M` memory is free because `683M` is buffered or cached and `161M` is used. I believe dashboard works correctly. Let me know if you find anything unusual.

**Comment by douglasmiranda** [comment]
Oh, I see. But I think it would be better if the dashboard shows the "used" memory.

The way it shows now, it leads me to think I would have to add memory to the server, that abstruse itself was using that memory. Because I just started and nothing else was running.

**Comment by vniche** [comment]
Is there `available` listed on possible methods for memory stats? It acctually shows `free + cached/buffered` memory, maybe it's a way.

About using swap, it depends on your use, on a dedicated server i would advise against using it, `swap` is the `the last man standing` of memories, and it`s already a half-dead. :p

**Comment by irmana** [comment]
@vniche and @douglasmiranda 
we will revisit this issue in following one week and provide an answer whether we found a pragmatic solution that fits into `2.0` release.

**Comment by d2dyno** [comment]
Seeing this issue as well, showing as 95% used, when in reality only 15% is in use.
