### ISSUE TITLE
Can't clone repository from bitbucket after some time

### ISSUE THREAD

**Issue by dedkat** [bleenco/abstruse#385]
Hi, this's happening second time and it's weird. After more than 40 builds abstruse can't clone repository. "Check repository Configuration" works fine, also fetching config works as well. But in build I got error:

remote: Invalid username or password. If you log in via a third party service you must ensure you have an account password set in your account profile.
fatal: Authentication failed for 'https://bitbucket.org/***********************'

[error]: executed command returned exit code 128

**Comment by jkuri** [comment]
that is really weird and I don't have an answer for this issue. do you know how to reproduce this problem so problem is there each time? "check repository config" and "fetching config" also clones repository so I am not sure what that could be.

**Comment by dedkat** [comment]
Have no idea, previously I could not add new bitbucket credentials and delete old one - so I just run new container with new configuration. It's probably not db issue because I copied abstruse.sqlite file from yesterday but that didn't help.

**Comment by jkuri** [comment]
you also need to copy `config.json` file.

**Comment by dedkat** [comment]
Ok, I got this error again but in different situation ;)
Now I can't clone repo if I try to relaunch merged build. Other builds works fine.

**Comment by irmana** [comment]
@dedkat did you manage to resolve this issue?

**Comment by dedkat** [comment]
@irmana no there is still problem with that, but I didn't work with abstruse lately. Last time when it happens I had only to add another access token to bitbucket and it start work correctly.

**Comment by irmana** [comment]
Thanks @dedkat, 
@jkuri we have to check it and add this issue to 2.0 release.

**Comment by jkuri** [comment]
I had this on tasklist in the head :)
