### ISSUE TITLE
[bug] a few bugs and propositions of enhancements

### ISSUE THREAD

**Issue by dedkat** [bleenco/abstruse#388]
Bugs:

- can’t “echo” or “cat” anything - often I have to display some information 
- stages after_failure and after_successful - don't work for me at all - after successes build it runs "after_failure" ;)
- images - shows the same size for all base images
- can't easy change directory - you have to write commands sequence in one line to keep current path 
- after rebasing feature branch abstruse start build master branch - this one is very important 
- in debug mode, after logging on ssh we don't have access to environment variables
- after merging to master abstruse start to build master ...but it's version before merging - this one is very important 

Enhancements:

- groups for users (or teams)
- permissions to repositories for users/groups
- more elastic web hook’s - like in gitlab - would be nice, sometimes I want to trigger different repo to not keep two pipelines
- scheduled builds and triggered builds - allow to set scheduled build and allow to trigger another build (different repositories) without pushing to repo - it's possible in gitlab
- smaller base image without sshd and vnc - alpine?
- option to not download repo in "deploy" stage
- CLI to manage abstruse from command line

**Comment by jkuri** [comment]
wow, thanks a lot @dedkat for that. really nice list of bugs and future improvements. if you don't mind I'll use this issue as a milestone for `2.0.0` release?

**Comment by dedkat** [comment]
Hi, no problem take your time, I really want to start use abstruse on production, but for now those two bugs marked as important make it impossible.
I can bypass problem with building old version of master branch after merging, but I can't do the same with rebasing issue :/

**Comment by ad-m** [comment]
> scheduled builds and triggered builds - allow to set scheduled build and allow to trigger another build (different repositories) without pushing to repo - it's possible in gitlab

 See https://confluence.atlassian.com/bitbucket/scheduled-pipelines-933078702.html how Bitbucket pipelines handled that.
