### ISSUE TITLE
[feat] Runner configuration

### ISSUE THREAD

**Issue by magyarosibotond** [bleenco/abstruse#389]
Add ability to configure Jenkins or Gitlab like runners.

- Add ability to configure multiple build machines with docker support.
- Add ability to add runners without docker. (handy for projects with no docker support: iOS)
- Add ability to tag runners.

**Comment by jkuri** [comment]
Hi! I am not completely sure that I understand what you had in mind with this issue. 
If I am correct, you would like to control Jenkins or GitLab runner from `abstruse`?
Also, the whole idea of `abstruse` is based on `docker`, so the second point is completely off if you ask me.

**Comment by jkuri** [comment]
That would make sense but first we would need plugin system as you said. 
Currently, for the `2.0.0` release there is a [list](https://github.com/bleenco/abstruse/issues/388) of features and bugs that need to be fixed, I would add refactor of UI to that list also so we are planning this to be done till the end of this summer.

If you have any experience with writing a plugin system, I could create a separate branch where we can develop this in parallel. First, I would start with some rough specifications how that would work in some markdown file, we could place it in `docs/design/plugin-system.md` and later in `docs/specification/plugin-system.md` when we make a decision what features would be included and everything. 
You hand here would be very appreciated, thanks!

**Comment by magyarosibotond** [comment]
I have no prior experience in that field, but I’m more than happy to do a quick research. 😊

**Comment by jkuri** [comment]
okay, you can let me know if you find some good samples or/and best practices. then we can define design and specifications together.
