### ISSUE TITLE
[feat]: speedup clone of big repositories (2.0 release)

### ISSUE THREAD

**Issue by aleho** [bleenco/abstruse#391]
Hi!

I know this sort of special, but on very big repositories cloning may take ages.

I'm currently looking for a maintainable way to not clone but fetch from an already existing repo.
Having the repo checked out locally and providing it as a volume might do the trick (also manually changing the clone URL?), but that doesn't sound too elegant.

Is there something I'm missing here?

Ultimately I'd like to be able to
a) Not clone a big repository entirely, just fetch a branch / ref without depth (e.g. `git fetch origin $REF --depth=1`).
b) Start the git checkout from an already existing directory (e.g. a volume) that $host can provide.

**Comment by jkuri** [comment]
Hi!

This sounds like a reasonable improvement in the future, but we need to find a way good way to implement that. If you have any suggestions I'll put this feature in the `2.0` release.

**Comment by aleho** [comment]
Oh, and I forgot to mention:
A configuration for `--depth=1` and `--shallow-submodules` might be a good thing anyway (normally I don't need any commit history for testing).

**Comment by jkuri** [comment]
@aleho, I accepted your feature request and put it in the `2.0` release which we expect to be done in the end of August or mid September.

There is many bugs needs to be fixed before I'll start implementing new features.
Do you want to be informed when I'll come to this feature and help me test it? I would appreciate any help.

btw, I just started with the new web UI for the weekend if you are interested how things will look in the future [here](https://github.com/bleenco/abstruse/issues/393) you can track progress and see initial screenshots.

Thanks!

**Comment by aleho** [comment]
I'd love to help testing! Just ping me.

Unfortunately my private time is limited atm, but maybe I can dedicate a few hours at work. I'll have a look at the code base and see if I can help with contributions.
