### ISSUE TITLE
[feat]: new user interface for 2.0 release

### ISSUE THREAD

**Issue by jkuri** [bleenco/abstruse#393]
Issue to track progress on new user interface which will be release with `2.0`.

**screens**
- [x] initial setup
- [x] builds history
- [ ] dashboard
- [x] team management
- [ ] repositories management
- [x] docker images management
- [ ] user settings
- [ ] system logs

**unit tests coverage**
- [x] initial setup
- [ ] builds history
- [ ] dashboard
- [ ] team management
- [ ] repositories management
- [ ] docker images management
- [ ] user settings
- [ ] system logs

**e2e tests coverage**
- [x] initial setup
- [ ] builds history
- [ ] dashboard
- [ ] team management
- [ ] repositories management
- [ ] docker images management
- [ ] user settings
- [ ] system logs

**Comment by jkuri** [comment]
This week I started working on the new UI and this is something I came up with:
![screen shot 2018-08-06 at 17 05 54](https://user-images.githubusercontent.com/1796022/43724744-0caf4972-999b-11e8-8f21-4289641e8916.png)
![screen shot 2018-08-06 at 17 06 09](https://user-images.githubusercontent.com/1796022/43724757-12355c1a-999b-11e8-8277-32e389e7f56e.png)

**Comment by ForsakenHarmony** [comment]
so uhh, what about the beta release in august? 👀
