### ISSUE TITLE
Installing abstruse from source, npm error ENOENT: no such file or directory

### ISSUE THREAD

**Issue by yunusem** [bleenco/abstruse#397]
I am getting these error that i could not figure out how to solve it since 2 days. I switched host systems 3 times. The **output** below is from [Ubuntu 18.04](http://releases.ubuntu.com/18.04/) . I am getting exactly the same results with [Pardus 17.3](https://www.pardus.org.tr/)
and [Debian 9.4](https://www.debian.org/News/2018/20180310) . Can anybody help me with this ?

`vagrant@ubuntu-bionic:~/projects/abstruse$ lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

`vagrant@ubuntu-bionic:~/projects$ git clone https://github.com/bleenco/abstruse.git`
```
Cloning into 'abstruse'...
remote: Counting objects: 10019, done.
remote: Total 10019 (delta 0), reused 0 (delta 0), pack-reused 10018
Receiving objects: 100% (10019/10019), 9.99 MiB | 3.23 MiB/s, done.
Resolving deltas: 100% (7069/7069), done.
```
`vagrant@ubuntu-bionic:~/projects$ cd abstruse/`

`vagrant@ubuntu-bionic:~/projects/abstruse$ npm i`
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! path /vagrant/abstruse/node_modules/bcrypt/node_modules/tar/node_modules/yallist/package.json.999934972
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/vagrant/abstruse/node_modules/bcrypt/node_modules/tar/node_modules/yallist/package.json.999934972'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2018-08-15T07_41_54_369Z-debug.log
```

`vagrant@ubuntu-bionic:~/projects/abstruse$ npm version `
```
{ abstruse: '1.6.4',
  npm: '6.2.0',
  ares: '1.14.0',
  cldr: '33.1',
  http_parser: '2.8.0',
  icu: '62.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.32.0',
  node: '10.8.0',
  openssl: '1.1.0h',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.22.0',
  v8: '6.7.288.49-node.19',
  zlib: '1.2.11' }
```

**Comment by jkuri** [comment]
did you install `sudo apt-get install build-essential` before running `npm install`?

**Comment by yunusem** [comment]
Of-course, i am not a newbee man :), i assume you guys can observe the same result on latest ubuntu or debian vagrant images.

**Comment by jkuri** [comment]
For me its working fine with latest ubuntu bionic. Never tried running in vagrant though, but seems like this is not related to abstruse directly but to one of the dependencies, bcrypt I guess.

**Comment by yunusem** [comment]
I think the same, but the approach is here that when we want to follow the installation [documents](https://github.com/bleenco/abstruse/blob/master/docs/INSTALLATION.md#install-from-npm), it does not work. Thats why i opened the issue so that maybe you could look into it. If you have a spare time to use any virtual or physical machine that runs fresh debian derivative, it will not work. In the mean time i am using another physical machine (ubuntu/bionic) to install and the result is still the same.

**Comment by jkuri** [comment]
thanks for this report. I think it is a `npm` issue if you run this as root user. Please try with:
```sh
npm i abstruse --unsafe-perm -g
```

**Comment by yunusem** [comment]
`sudo npm i abstruse --unsafe-perm -g`
```
npm WARN deprecated uws@10.148.2: stop using this version
/usr/local/bin/abstruse -> /usr/local/lib/node_modules/abstruse/dist/api/index.js

> ursa-ssl@1.0.0 install /usr/local/lib/node_modules/abstruse/node_modules/ursa-ssl
> node-gyp rebuild

make: Entering directory '/usr/local/lib/node_modules/abstruse/node_modules/ursa-ssl/build'
  CXX(target) Release/obj.target/ursaNative/src/ursaNative.o
  SOLINK_MODULE(target) Release/obj.target/ursaNative.node
  COPY Release/ursaNative.node
make: Leaving directory '/usr/local/lib/node_modules/abstruse/node_modules/ursa-ssl/build'

> bcrypt@2.0.1 install /usr/local/lib/node_modules/abstruse/node_modules/bcrypt
> node-pre-gyp install --fallback-to-build

[bcrypt] Success: "/usr/local/lib/node_modules/abstruse/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remote

> sqlite3@4.0.2 install /usr/local/lib/node_modules/abstruse/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/usr/local/lib/node_modules/abstruse/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" is installed via remote
+ abstruse@1.6.4
added 303 packages from 238 contributors in 24.015s
```

`abstruse`
```
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'uws'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/abstruse/dist/api/index.js:361:161873)
    at n (/usr/local/lib/node_modules/abstruse/dist/api/index.js:2:110)
    at Object.<anonymous> (/usr/local/lib/node_modules/abstruse/dist/api/index.js:361:161975)
    at n (/usr/local/lib/node_modules/abstruse/dist/api/index.js:2:110)
    at Object.<anonymous> (/usr/local/lib/node_modules/abstruse/dist/api/index.js:648:55155)
    at n (/usr/local/lib/node_modules/abstruse/dist/api/index.js:2:110)
    at /usr/local/lib/node_modules/abstruse/dist/api/index.js:2:517
    at Object.<anonymous> (/usr/local/lib/node_modules/abstruse/dist/api/index.js:2:528)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

`sudo npm i uws -g`
```
npm WARN deprecated uws@99.0.0: stop using this version
+ uws@99.0.0
added 1 package in 0.402s
```

It throws an error related to **uws** package again. I think you guys have problems with the latest npm and proper package dependencies. By the way i **can** use abstruse with docker image, i just wanted to investigate your great work and contribute if i may.

**Comment by jkuri** [comment]
@yunusem nice catch, you can do `npm install uws@10.148.0` or clone the master and run clean install. on npm this is broken, you are right.
your help is always welcome, I am currently implementing new UI for abstruse `2.0` so please wait so I finish that and prepare pull request for it. Don't worry, the list of bug fixes and new features is long for 2.0 version which will be the next release... so we never get out of tasks :)

btw, here's peak of the new UI that I am prepairing, would like to hear your opinion on that:
![screen shot 2018-08-16 at 10 14 39](https://user-images.githubusercontent.com/1796022/44196802-37708c80-a13d-11e8-9992-99edba82eeb1.png)

**Comment by yunusem** [comment]
Yeah it looks more material design based (its cool). I am looking forward to see at least developer friendly version 2.0. I am planing to fork your project to start up 
ci,  review, wiki and issue tracker combined node js project myself. Thanks @jkuri

**Comment by irmana** [comment]
@yunusem would you be interested to join us next week in our planning session and help releasing developer friendly 2.0?

**Comment by yunusem** [comment]
Hey @irmana, i would like to but in Turkey there is a Holiday upcoming in next week. Considering coding, I do not think I can make any other contribution from looking at the project from another perspective since i am not as experienced as you at node.js yet. I am more like well trained and experienced on qt environment and cpp but i am into js and ts and learning.

**Comment by irmana** [comment]
@yunusem let's follow up after your holidays. I think you could still be useful. ;)
