### ISSUE TITLE
(non amd64 support) Running abstruse on aarch64 [odroid c2]

### ISSUE THREAD

**Issue by k1r0s** [bleenco/abstruse#413]
Hey, I just follow the installation tutorial

Im running an Odroid c2

`$ uname -a`

> Linux odroid64 3.14.79-116 #1 SMP PREEMPT Tue Sep 26 01:19:06 BRT 2017 aarch64 aarch64 aarch64 GNU/Linux

distro: http://de.eu.odroid.in/ubuntu_16.04lts/ubuntu64-16.04.3-minimal-odroid-c2-20171005.img.xz

Everything went smooth until I run the last command: 

`root@odroid64:~# docker run -dit --restart always -v /var/run/docker.sock:/var/run/docker.sock -v ~/abstruse-config:/root/abstruse -p 6500:6500 bleenco/abstruse`

It appears that the image is restarting over and over again:

![image](https://user-images.githubusercontent.com/6052309/45545442-913aa400-b81a-11e8-8b2f-a4ad71e2c56f.png)

Any ideas about how to find the real issue? Thanks!

**Comment by jkuri** [comment]
hi @k1r0s. Docker image is built for `amd64` and not `aarch64`. If you'd like to run this on `aarch64` you will need to build image from source.

**Comment by k1r0s** [comment]
Gracias amigo

**Comment by k1r0s** [comment]
I realized that the error is on this line

`The command '/bin/sh -c apk --no-cache add openssl' returned a non-zero code: 1`

**Comment by k1r0s** [comment]
mmm im not into docker but it seems that base node image on top of Alpine Linux isn't working https://hub.docker.com/r/mhart/alpine-node/

```
root@odroid64:~/abstruse# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              64f589deb03b        9 minutes ago       68.2MB
mhart/alpine-node   10                  2882d817e6d6        2 days ago          68.2MB
mhart/alpine-node   latest              2882d817e6d6        2 days ago          68.2MB
root@odroid64:~/abstruse# docker run mhart/alpine-node node --version
standard_init_linux.go:190: exec user process caused "exec format error"
root@odroid64:~/abstruse# 

```

**Comment by k1r0s** [comment]
base image should be aarch64 too?

**Comment by k1r0s** [comment]
it works with https://hub.docker.com/r/arm64v8/node/

**Comment by k1r0s** [comment]
node sqlite3 has issues supporting non amd64 architectures

![image](https://user-images.githubusercontent.com/6052309/45597345-12389d80-b9cb-11e8-822a-bb9bfcadf46b.png)

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Linux 3.14.79-116
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/app/node_modules/sqlite3/lib/binding/node-v64-linux-arm64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/app/node_modules/sqlite3/lib/binding/node-v64-linux-arm64" "--napi_version=3" "--node_abi_napi=napi"
gyp ERR! cwd /app/node_modules/sqlite3
gyp ERR! node -v v10.10.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-09-16T14_04_49_149Z-debug.log

``` 

I swear abstruse can use another persistance database rather than sqlite3

**Comment by k1r0s** [comment]
fyi https://github.com/mapbox/node-sqlite3/issues/903
