### ISSUE TITLE
Deploy to cloud foundry

### ISSUE THREAD

**Issue by ellavas** [bleenco/abstruse#426]
Hello,

I'm trying to install abstruse to a cloud foundry instance. I have deployed the docker image to cloud foundry by running 
`cf push abstruse-ci --docker-image bleenco/abstruse`

The instance is started and I can browse the setup page. But docker is marked as not running.

Do I missed something in the configuration ? Or do I have to use a custom dockerfile ?

Thanks in advance.

**Comment by jkuri** [comment]
hi. instance on cf needs to have docker running inside.

**Comment by ellavas** [comment]
Hi,

How can I check that ? 
Docker is marked as installed and I pushed abstruse from the docker image so I thought everything is available ?

I found some errors in the log about Tini

>    2018-10-09T16:47:19.70+0200 [CELL/0] OUT Cell e6d12eda-76ac-4a8f-a78b-24744f0e57eb successfully created container for instance 0b8349b5-c507-4cd6-79e5-29d2
>    2018-10-09T16:47:20.05+0200 [CELL/0] OUT Starting health monitoring of container
>    2018-10-09T16:47:20.11+0200 [APP/PROC/WEB/0] ERR [WARN  tini (8)] Tini is not running as PID 1 and isn't registered as a child subreaper.
>    2018-10-09T16:47:20.11+0200 [APP/PROC/WEB/0] ERR Zombie processes will not be re-parented to Tini, so zombie reaping won't work.
>    2018-10-09T16:47:20.11+0200 [APP/PROC/WEB/0] ERR To fix the problem, use the -s option or set the environment variable TINI_SUBREAPER to register Tini as a child subreaper, or run Tini as PID 1.
>    2018-10-09T16:47:20.97+0200 [APP/PROC/WEB/0] ERR (node:19) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
>    2018-10-09T16:47:21.37+0200 [APP/PROC/WEB/0] OUT [2018-10-09 14:47:21]: [server]: starting Abstruse CI version 1.6.5 ...
>    2018-10-09T16:47:21.37+0200 [APP/PROC/WEB/0] OUT [2018-10-09 14:47:21]: [server]: API and Socket Server running at port 6500
>    2018-10-09T16:47:21.37+0200 [APP/PROC/WEB/0] OUT [2018-10-09 14:47:21]: [encrypt]: RSA public and private key successfully generated
>

**Comment by jkuri** [comment]
Can you try changing permissions of `/var/run/docker.sock` to less restrictive and let me know if that works?

**Comment by ellavas** [comment]
I'm not the administrator of the cloud foundry platform, so I can't change the permission.
Is there any option to pass to the cf push command ?

Thanks
