### ISSUE TITLE
Running abstruse on relative path

### ISSUE THREAD

**Issue by mayank** [bleenco/abstruse#438]
Hi,
 I am running abstruse on a server where there are more things deployed so I want to use a relative url like example.com/abstruce/ but currently if I am doing that assests are loading on example.com and not on example.com/abstruce/.

**Comment by mayank** [comment]
@jkuri ?

**Comment by jkuri** [comment]
sorry I closed multiple issues as we are about to release v2 and old issues were about v1, should not do that anyway without message.
