### ISSUE TITLE
Can't setup Bitbucket Cloud integration

### ISSUE THREAD

**Issue by danieleratti** [bleenco/abstruse#444]
I followed the procedure described in the issue #394 but Abstruse still can't fetch the repo.

I created an OAuth app, setted up the OAUth Client ID as my username (not e-mail), OAuth key and secret... Then I've chosen up the correct Bitbucket auth token in the repo setting.

It gets the webhooks correctly but when I try to verify the configuration I still get the following error..

How is possible to debug it?

<img width="586" alt="schermata 2019-02-21 alle 00 39 40" src="https://user-images.githubusercontent.com/1781218/53132876-80cce900-3571-11e9-8549-6c0c0499aac2.png">

**Comment by gbourgeat** [comment]
Try to replace your client id by "x-token-auth"
