### ISSUE TITLE
[question] run different scripts depending on branch being built

### ISSUE THREAD

**Issue by arcln** [bleenco/abstruse#446]
For example, I'd like to run some custom script only for the `production` branch.

EDIT: I hacked this by using:

```bash
if [[ $(git rev-parse --abbrev-ref HEAD) == "production" ]]; then dostuff; fi
```

**Comment by paullaffitte** [comment]
Maybe you should look at [docs/ENV_VARIABLES.md](https://github.com/bleenco/abstruse/blob/master/docs/ENV_VARIABLES.md). There is a `ABSTRUSE_BRANCH` pubilc env variable defined for each builds.

**Comment by arthurchaloin** [comment]
Here's the output of `env` from the container:

![output](https://i.imgur.com/btVxXrW.png)

As you can see, there is not even half of the variables that should be there. The more interesting thing is that only one out of two of the variables I manually defined are displayed - even if I can use both of them during build without any issue. Is that a display bug?

**Comment by gergof** [comment]
I guess it's a display bug. It works just right for my pipeline.
