### ISSUE TITLE
Is it possible to build images with different ubuntu versions 

### ISSUE THREAD

**Issue by orensbruli** [bleenco/abstruse#458]
Is it possible to build images with ubuntu 18.04 or 19.08?
How do I build those images from abstruse web interface?

**Comment by gergof** [comment]
You need to make a new base image using those versions. Everything should be compatible as far as I know. After that you can make new custom images based on that base image.

![image](https://user-images.githubusercontent.com/10323997/76522674-a7f1a380-646f-11ea-8242-ea05bcc41afb.png)

**Comment by orensbruli** [comment]
Thank you!
