### ISSUE TITLE
Github Organization

### ISSUE THREAD

**Issue by gastrodon** [bleenco/abstruse#469]
Looking at the server brought up by the instructions in the README, I'm not seeing how to add a github organization that I own. Is this possible?

**Comment by jkuri** [comment]
If you are using version from master branch, you need to add scm provider. 
Go to providers and add GitHub provider with your github access token, you can generate it on github on settings -> developer settings -> personal access tokens. After you add SCM provider click on sync to synchronize repositories. Then you can trigger a build under repository settings.

**Comment by gastrodon** [comment]
I'm aware that I can add an scm provider. Adding a provider pointing towards github's api with a token bound to my account just seems to show repositories on my account, but no organizations

**Comment by gastrodon** [comment]
I've solved this issue myself, I was just neglecting to add org:read
permissions to the github access token
