### ISSUE TITLE
feat: environment variables

### ISSUE THREAD

**Issue by jkuri** [bleenco/abstruse#486]
we need to add feature that allows you to manage environment variables on repository for both public and secret ones.

**Comment by MrCyjaneK** [comment]
Also console output should hide the secret variables if they get printed to console.

**Comment by jkuri** [comment]
@MrCyjaneK I disabled to print secret variables to the console here https://github.com/bleenco/abstruse/pull/489/commits/e21d3be90e4cce6ecc262bda7dc6cc54a064ee0a
