### ISSUE TITLE
Shows only blank page after first login when using Firefox

### ISSUE THREAD

**Issue by espenaf** [bleenco/abstruse#499]
First login work ok, but every page after that fails in Firefox 84 with just a blank page.

Firefox console shows the following errors:

    Loading failed for the <script> with source “https://ci.abstruse.cc/main.5b35a971c94f06429bc0.js”. ci.abstruse.cc:16:1
    Failed to load 'https://ci.abstruse.cc/main.5b35a971c94f06429bc0.js'. A ServiceWorker intercepted the request and encountered an unexpected error. ngsw-worker.js:2041:18

Before trying to create an issue at Mozilla, I wanted to check if this related to how the UI in Abstruse is implemented. I found this link that might be related https://stackoverflow.com/questions/63535778/angular-firestore-a-serviceworker-intercepted-the-request-and-encountered-an

**Comment by jkuri** [comment]
Tried now with Firefox 85.0 and cannot reproduce the error, can you try deleting your cache?

**Comment by espenaf** [comment]
1. Go page login page, and it works fine
2. Logging in and using the site works fine.
3. Close the tab, create new one for the same site, then I get a blank page.
4. Clear all data for site 
5. Then i can login as in step 1 again.

Clearing the cookie is not enough, I need to clear it all to the back into the site.

**Comment by espenaf** [comment]
Works without issues on Fedora 33 and Firefox 84. Closing
