### ISSUE TITLE
(Feature Request) Allow Docker-Volumes in builder image

### ISSUE THREAD

**Issue by Marcel2508** [bleenco/abstruse#501]
It would be nice to allow mounting of docker-volumes inside the image defined in abstruse.yml
Adding another value (mounts) or similar.
This could also allow to mount host's folders or else.

This could be useful for automatic deployment on the same host via docker.

Caveat would be that an attacker with access to the git repo could gain access to host by modifying abstruse yaml and adding evil commands.

**Comment by jkuri** [comment]
hi @Marcel2508, as you mention below that will be very big security risk if we allow to mount /var/run/docker.sock directly to running jobs. I guess there is no way to ensure that attackers would not be able to do any damage if we enable this option so I will close this issue.
