### ISSUE TITLE
How to use sqlite?

### ISSUE THREAD

**Issue by helmut72** [bleenco/abstruse#515]
From Quickstart:

```
database name (file name when sqlite client used) (default "abstruse")
```

When trying:
```
- ABSTRUSE_DB_DRIVER=sqlite
```

Output is:
```
ERROR	database connection issue: sql: unknown driver "sqlite" (forgotten import?)	{"type": "db"}
```

Thanks!

**Comment by jkuri** [comment]
Hi @helmut72, I will create a PR for that soon, and then it will be possible with `--db-driver sqlite3`.

**Comment by helmut72** [comment]
Hi @jkuri, thanks. I want to use it on a device with low RAM and read later, that SQLite was removed in Abstruse 2.0, I searched for an alternative and use this now.
