### ISSUE TITLE
Automated building?

### ISSUE THREAD

**Issue by cheetahbyte** [bleenco/abstruse#520]
I have two questions, somehow the builds are not automated when committing. Is this some kind of hidden setting? How can I set this?
The second question:
Is it possible to upload a package directly to pyPi after building it? 
Thanks in advance

**Comment by jkuri** [comment]
if you meant that builds are not automatically triggered, then you missed something when configuring webhooks. 
please follow the steps from [here](https://github.com/bleenco/abstruse/blob/master/docs/INTEGRATING_GIT_PROVIDERS.md) and check that you set correct secret. You can also check webhook history to see what went wrong or abstruse console log. Please let me know if you managed to configure it properly.

**Comment by inkvizitor68sl** [comment]
@pyalpha 
Hi, we had problems with autobuilds too (due to incorrect webhook updates for github).
Now it fixed - https://github.com/bleenco/abstruse/issues/525
If you are still interested - try now )

**Comment by cheetahbyte** [comment]
Thank you very much, that helped me :)
