### ISSUE TITLE
Button/link to see build log as simple plain text?

### ISSUE THREAD

**Issue by inkvizitor68sl** [bleenco/abstruse#521]
First of all, thanks for great CI - it is really uniq for now around other monsters - simple, fast, easy, but has everything we need to dive in CI in 2021. 

I see now small issue - job log now is not a "just text". So we can't copy part of it, cant find some text inside log and etc. 
Also it looks like size of job log is limited by some amount of characters in abstruse frontend. 

However this console looks great when all jobs is successfull, but this makes some hurt, when jobs are not passed =) 

Probably it is some local browser problem, but i tested few of them (at least Chromium 91/Firefox 76) - all of them has same problems. 

So it would be great to add "download job log" button for each job to be able make some debug around job logs. 
Ofc it would be great to fix text search/copying - but i understand, that it can be something hard to fix.

**Comment by inkvizitor68sl** [comment]
Currently i use something like that: 
```#!/bin/bash

# where $1 is build number in Abstruse
mysql -e "select log from ci.jobs where build_id = ${1} \G"
```
when plain text is needed

**Comment by jkuri** [comment]
hi @inkvizitor68sl, thanks for your positive feedback! I will implemented that feature to view raw logs on the user interface soon, probably this weekend already, but not sure.

**Comment by jkuri** [comment]
Hi @inkvizitor68sl I implemented you feature request about viewing raw logs, here's the demo:

https://user-images.githubusercontent.com/1796022/121754954-33942d00-cb16-11eb-977c-dc0ab3e853d2.mp4
