### ISSUE TITLE
Abstruse updates webhook for github repositories with incorrect provider secret

### ISSUE THREAD

**Issue by inkvizitor68sl** [bleenco/abstruse#525]
There are few situations, when Abstruse updates webhook settings at github repository: 
- when we switch "Enabled" flag at /repos page
- when we switch "Build pushed branches/PRs/tags" at /repos/ID/settings page

When we do some of this - http(s) request generated to https://ci_domain/api/v1/repos/ID/hooks

Here HandleCreateHooks() from api/repo/create_hooks.go called (router.Put("/{id}/hooks", repo.HandleCreateHooks(r.Repos)))

But when it hapennes - auto-builds not work anymore, until i go to webhook settings at github repository and manually update "Secret" field at github to value from "Secret" field at Abstruse provider settings. 

Unfortunally, i can't see exact content of secret field at github stored after /{id}/hooks to debug more information, but ready to do some debug, if you say what to change at sources (debug logs already enabled).

abstruse/abstruse-server:latest docker image used

**Comment by inkvizitor68sl** [comment]
I found, that value "Secret" sends to github API instead of real secret value from database in this case.

**Comment by jkuri** [comment]
I cannot reproduce that issue, you need to set secret on provider you have added, if you entered `Secret` there then this string is used, because I was looking for hardcoded `Secret` string and it does not exists.

**Comment by inkvizitor68sl** [comment]
@jkuri 
Sorry for wasted time, i edited my comment later. 
I saw, that 6 symbols used (instead of 12 symbols in secret), while used curl on real github, so just thought, that value "Secret" used (name of some var in this part of code). 

But when autobuilds stopped again, i made more debug - started fake github API server and used debug tools to see JSON, which sends to github API, when hook update hapennes. 

I saw this JSON in some moment: 
```
{"name":"web","events":["push","pull_request","create","delete"],"active":true,"config":{"url":"https://<censored>/webhooks","secret":"github","content_type":"json"}}
```
Problem part here is "secret":"github" (i had another secret value at provider settings for that moment). 
So i replaced secret with value "github" in provider settings and tested autobuilds more carefully - they work now, when i change settings in CI.

**Comment by jkuri** [comment]
no problem, please close the issue if its working for you now.

**Comment by inkvizitor68sl** [comment]
@jkuri 
em. Sorry, but it works only if we use "github" secret value =) 
When we use another value - Abstruse still updates hook settings at github API with secret value "github".

We will do more debug to find problem exactly, but it is not good to close issue now, i think.

**Comment by jkuri** [comment]
You need to set secret on github same as you set on provider on abstruse,
they must match.

**Comment by inkvizitor68sl** [comment]
@jkuri 
yep, i understand that.

But there are events, when Abstruse changes webhook settings via github API (described at first message) - Abstruse will delete webhook from github repo settings via github API and will add new webhook to github repo (we can see that easily because each time we change settings at CI github webhook ID changes). 

And when that happenes - Abstruse creates webhook with secret value "github" via github API ("name" field of table providers probably) instead of real value ("secret" field of table providers). 
I cant say exactly right now is it hardcoded value or wrong field from table selected

**Comment by jkuri** [comment]
okay I understand now what is the issue, thanks for explanation 👍 I will
check into that, in the meantime please manually configure webhooks on
github if you guys are in hurry.

**Comment by inkvizitor68sl** [comment]
Okay, thank you!

It is not hurry ofc and i can not ask something hurry here =) 

Just if someone will face same problem - he can read this issue to see some workaround (not secure, but firewalls will help), i didnt mean nothing more, when created this (same about my other issues).

**Comment by jkuri** [comment]
@inkvizitor68sl thank you, if you encounter another issues just feel free to open it and we can discuss about it and fix them.

**Comment by jkuri** [comment]
I cannot reproduce this issue, I also tried printing out secret that is used when enableing hooks [here](https://github.com/bleenco/abstruse/blob/master/server/store/repo/repo.go#L218) so I added:
```go
fmt.Println(repo.Provider.Secret)
```
after this line and test it, result was:

![Screenshot 2021-06-13 at 16 33 59](https://user-images.githubusercontent.com/1796022/121811606-2d609680-cc65-11eb-926d-d0012bd05ddb.png)

Can you please check you configuration again under providers:

![Screenshot 2021-06-13 at 16 34 49](https://user-images.githubusercontent.com/1796022/121811650-55e89080-cc65-11eb-999e-a6f44c9dc19f.png)

Do you maybe have here `Github` configured?

**Comment by inkvizitor68sl** [comment]
@jkuri 
Hi 
It looks, like after https://github.com/bleenco/abstruse/commit/272c2300d9561ba461c28a54adb545668975d05c we have correct secrets on updated webhooks

So issue is resolved now for our instance

Thanks!
